#!/usr/bin/env bash
mkdir -p dist
echo "build src/state.styl -> dist/state.css ..."
./node_modules/.bin/stylus -p src/state.styl > dist/state.css
echo "minifying state.css ..."
./node_modules/.bin/uglifycss dist/state.css > dist/state.min.css
echo "deploy into local web ..."
mkdir -p web/static/assets/lib/state.css/
cp -R dist/* web/static/assets/lib/state.css/
echo "done."

